# Generated by Django 4.0.4 on 2022-06-04 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grants', '0002_grantleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_type', models.CharField(choices=[('CONFIRM', 'Confirm'), ('REJECT', 'Reject'), ('STANDBY', 'Standby')], default='STANDBY', max_length=20)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='grants.grantleave')),
            ],
        ),
    ]
