# Generated by Django 4.0.4 on 2022-06-04 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='order',
            new_name='grant_leave_id',
        ),
    ]
