# Generated by Django 4.0.4 on 2022-06-04 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signs', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaves', '0002_alter_leave_consume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.FloatField(verbose_name='부여된 휴가 일 수')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='휴가 대상자')),
            ],
        ),
        migrations.CreateModel(
            name='GrantLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grants.grant')),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='leaves.leave')),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order', verbose_name='신청 정보')),
                ('sign', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='signs.sign', verbose_name='승인 정보')),
            ],
        ),
    ]
