# Generated by Django 4.0.4 on 2022-06-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0002_grantleave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='stock',
            field=models.FloatField(verbose_name='부여된 휴가 일 수'),
        ),
    ]
