# Generated by Django 4.0.4 on 2022-06-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0001_initial'),
        ('orders', '0002_order_consume_order_is_all_day_alter_order_end_date_and_more'),
        ('leaves', '0002_alter_leave_consume'),
        ('grants', '0002_remove_grantleave_grant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GrantLeave',
            new_name='OrderSign',
        ),
    ]
