# Generated by Django 4.0.4 on 2022-06-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0003_rename_grantleave_ordersign'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='설명'),
        ),
    ]
