# Generated by Django 4.0.4 on 2022-06-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='휴가 종류')),
                ('consume', models.IntegerField(verbose_name='소진일')),
            ],
        ),
    ]
