# Generated by Django 4.0.4 on 2022-06-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='consume',
            field=models.FloatField(verbose_name='소진일'),
        ),
    ]
