# Generated by Django 4.0.4 on 2022-07-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PushMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_key', models.CharField(choices=[('APPROVE', '휴가수락'), ('DENY', '휴가반려'), ('REQUEST', '휴가신청'), ('CANCEL', '휴가취소')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
