# 정적 파일이 위치하는 서버에 backports-zoneinfo 패키지를 추가로 설치한다 -> pip install backports-zoneinfo (poetry install 이후 설치)
# 미 설치시 collectstatic 명령이 안된다.

name: Docker Image CI

on:
  push:
    branches: [ feature/쿠버네티스_적용 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Image for Server
      run: | 
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }} 
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/leave:${GITHUB_SHA::7} --tag ${{ secrets.DOCKER_HUB_USERNAME }}/leave:latest --build-arg YOUR_ENV=production
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/leave:${GITHUB_SHA::7}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/leave:latest
    - name: Build Docker Image for Worker
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }} 
        docker build . --file DockerfileForWorker --tag ${{ secrets.DOCKER_HUB_USERNAME }}/leave_push_worker:${GITHUB_SHA::7} --tag ${{ secrets.DOCKER_HUB_USERNAME }}/leave_push_worker:latest --build-arg YOUR_ENV=production
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/leave_push_worker:${GITHUB_SHA::7}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/leave_push_worker:latest
# 테스트 배포를 위한 주석